# Generated by Django 4.0.6 on 2023-01-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_id_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('temperature', 'datetime_now')},
        ),
    ]
